### ISSUE TITLE
FEATURE: Add iati-data-bugtracker tickets alongside publishers

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/dashboard#28]
Where a publisher has associated tickets on [codeforIATI/iati-data-bugtracker](https://github.com/codeforIATI/iati-data-bugtracker/issues), we should display these on the Dashboard.

**Comment by matmaxgeds** [comment]
Would be nice if the Flashboard was an actual dashboard that pulled in all the relevant bits from other CfI (and other) products e.g. dashboard bits, bugs etc.....put in the publisher name, and see everything we know on them

**Comment by andylolz** [comment]
Something similar previously existed. It was removed in IATI/IATI-Dashboard PR 412.

**Comment by andylolz** [comment]
Aha! Something similar previously existed. Looks like it was removed in IATI/IATI-Dashboard PR 412.

**Comment by andylolz** [comment]
With codeforIATI/iati-data-bugtracker#18, this should be a bit more doable.
