### ISSUE TITLE
Rename the dashboard / be clear this is community run

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/dashboard#30]
I think it'd be useful to make some distinctions between the "community run" dashboard and the "official" one, so that users can be clear.

One way to do this would be by changing the title on the community dashboard... (not exactly sure what to!)....

**Comment by andylolz** [comment]
Thumbs up for IATI Flashboard.

Other suggestions, please post below!

**Comment by stevieflow** [comment]
IATI Board-dash ?

**Comment by andylolz** [comment]
For the timebeing at least, I’ve renamed the repo (from “IATI-Dashboard” to “dashboard”) and everywhere else I’ve changed “IATI Dashboard” to “Code for IATI Dashboard”.

**Comment by stevieflow** [comment]
THanks!

Maybe... also put the codeforIATI logo in the header - as per replicated codelists site.  Maybe.  Dunno

**Comment by andylolz** [comment]
Yeah, v good plan I think.

**Comment by andylolz** [comment]
Logo added:
![Screenshot 2021-04-01 at 13 40 41](https://user-images.githubusercontent.com/464193/113295242-dbf46c80-92ef-11eb-8718-e998d044bc5d.png)

Closing this!
